#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""\
Link To The Past - a backup tool

Starter script with a short name.

(C) 2012 cliechti@gmx.net
"""

from link_to_the_past.__main__ import main
main()
